import io
import re
from datetime import datetime

from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import cm
from reportlab.platypus import (
    HRFlowable,
    Paragraph,
    SimpleDocTemplate,
    Spacer,
)

STYLES = getSampleStyleSheet()
TITLE_STYLE = ParagraphStyle(
    "TitleStyle", parent=STYLES["Title"], fontSize=20, spaceAfter=6, textColor=colors.HexColor("#171d2b"),
)
META_STYLE = ParagraphStyle(
    "MetaStyle", parent=STYLES["Normal"], fontSize=9, textColor=colors.HexColor("#666666"), spaceAfter=14,
)
HEADING_STYLE = ParagraphStyle(
    "HeadingStyle", parent=STYLES["Heading2"], fontSize=13, spaceBefore=16, spaceAfter=8,
    textColor=colors.HexColor("#2f8f83"),
)
BODY_STYLE = ParagraphStyle(
    "BodyStyle", parent=STYLES["Normal"], fontSize=10.5, leading=15, spaceAfter=6,
)


def _escape(text: str) -> str:
    return (
        (text or "")
        .replace("&", "&amp;")
        .replace("<", "&lt;")
        .replace(">", "&gt;")
    )


def _markdown_inline(text: str) -> str:
    # LLM output uses simple **bold** markdown; reportlab Paragraph supports
    # a small HTML-like subset (including <b>), so translate that over.
    text = re.sub(r"\*\*(.+?)\*\*", r"<b>\1</b>", text)
    if text.startswith("- "):
        text = "• " + text[2:]
    return text


def _paragraphs(text: str):
    flowables = []
    for line in (text or "No content available.").splitlines() or [""]:
        line = line.strip()
        if not line:
            flowables.append(Spacer(1, 4))
            continue
        flowables.append(Paragraph(_markdown_inline(_escape(line)), BODY_STYLE))
    return flowables


def build_transcript_pdf(
    title: str,
    transcript: str,
    summary: str = "",
    key_points: str = "",
    action_items: str = "",
    key_moments: str = "",
) -> io.BytesIO:
    buffer = io.BytesIO()
    doc = SimpleDocTemplate(
        buffer,
        pagesize=A4,
        leftMargin=2.2 * cm,
        rightMargin=2.2 * cm,
        topMargin=2 * cm,
        bottomMargin=2 * cm,
        title=title or "Video Transcript",
    )

    story = [
        Paragraph(_escape(title or "Video Analysis Report"), TITLE_STYLE),
        Paragraph(f"Generated by Video Insight Studio on {datetime.now():%Y-%m-%d %H:%M}", META_STYLE),
        HRFlowable(width="100%", color=colors.HexColor("#dddddd")),
    ]

    sections = [
        ("Summary", summary),
        ("Key Points", key_points),
        ("Action Items", action_items),
        ("Key Moments", key_moments),
        ("Full Transcript", transcript),
    ]
    for heading, content in sections:
        if not content:
            continue
        story.append(Paragraph(heading, HEADING_STYLE))
        story.extend(_paragraphs(content))

    doc.build(story)
    buffer.seek(0)
    return buffer
